// DyedBrickType.java
package net.thejadeproject.asiandecor.blocks.custom;

import net.minecraft.world.item.DyeColor;

public enum DyedBrickType {
    // Generate all 256 combinations
    WHITE_WHITE(DyeColor.WHITE, DyeColor.WHITE),
    WHITE_ORANGE(DyeColor.WHITE, DyeColor.ORANGE),
    WHITE_MAGENTA(DyeColor.WHITE, DyeColor.MAGENTA),
    WHITE_LIGHT_BLUE(DyeColor.WHITE, DyeColor.LIGHT_BLUE),
    WHITE_YELLOW(DyeColor.WHITE, DyeColor.YELLOW),
    WHITE_LIME(DyeColor.WHITE, DyeColor.LIME),
    WHITE_PINK(DyeColor.WHITE, DyeColor.PINK),
    WHITE_GRAY(DyeColor.WHITE, DyeColor.GRAY),
    WHITE_LIGHT_GRAY(DyeColor.WHITE, DyeColor.LIGHT_GRAY),
    WHITE_CYAN(DyeColor.WHITE, DyeColor.CYAN),
    WHITE_PURPLE(DyeColor.WHITE, DyeColor.PURPLE),
    WHITE_BLUE(DyeColor.WHITE, DyeColor.BLUE),
    WHITE_BROWN(DyeColor.WHITE, DyeColor.BROWN),
    WHITE_GREEN(DyeColor.WHITE, DyeColor.GREEN),
    WHITE_RED(DyeColor.WHITE, DyeColor.RED),
    WHITE_BLACK(DyeColor.WHITE, DyeColor.BLACK),

    ORANGE_WHITE(DyeColor.ORANGE, DyeColor.WHITE),
    ORANGE_ORANGE(DyeColor.ORANGE, DyeColor.ORANGE),
    ORANGE_MAGENTA(DyeColor.ORANGE, DyeColor.MAGENTA),
    ORANGE_LIGHT_BLUE(DyeColor.ORANGE, DyeColor.LIGHT_BLUE),
    ORANGE_YELLOW(DyeColor.ORANGE, DyeColor.YELLOW),
    ORANGE_LIME(DyeColor.ORANGE, DyeColor.LIME),
    ORANGE_PINK(DyeColor.ORANGE, DyeColor.PINK),
    ORANGE_GRAY(DyeColor.ORANGE, DyeColor.GRAY),
    ORANGE_LIGHT_GRAY(DyeColor.ORANGE, DyeColor.LIGHT_GRAY),
    ORANGE_CYAN(DyeColor.ORANGE, DyeColor.CYAN),
    ORANGE_PURPLE(DyeColor.ORANGE, DyeColor.PURPLE),
    ORANGE_BLUE(DyeColor.ORANGE, DyeColor.BLUE),
    ORANGE_BROWN(DyeColor.ORANGE, DyeColor.BROWN),
    ORANGE_GREEN(DyeColor.ORANGE, DyeColor.GREEN),
    ORANGE_RED(DyeColor.ORANGE, DyeColor.RED),
    ORANGE_BLACK(DyeColor.ORANGE, DyeColor.BLACK),

    MAGENTA_WHITE(DyeColor.MAGENTA, DyeColor.WHITE),
    MAGENTA_ORANGE(DyeColor.MAGENTA, DyeColor.ORANGE),
    MAGENTA_MAGENTA(DyeColor.MAGENTA, DyeColor.MAGENTA),
    MAGENTA_LIGHT_BLUE(DyeColor.MAGENTA, DyeColor.LIGHT_BLUE),
    MAGENTA_YELLOW(DyeColor.MAGENTA, DyeColor.YELLOW),
    MAGENTA_LIME(DyeColor.MAGENTA, DyeColor.LIME),
    MAGENTA_PINK(DyeColor.MAGENTA, DyeColor.PINK),
    MAGENTA_GRAY(DyeColor.MAGENTA, DyeColor.GRAY),
    MAGENTA_LIGHT_GRAY(DyeColor.MAGENTA, DyeColor.LIGHT_GRAY),
    MAGENTA_CYAN(DyeColor.MAGENTA, DyeColor.CYAN),
    MAGENTA_PURPLE(DyeColor.MAGENTA, DyeColor.PURPLE),
    MAGENTA_BLUE(DyeColor.MAGENTA, DyeColor.BLUE),
    MAGENTA_BROWN(DyeColor.MAGENTA, DyeColor.BROWN),
    MAGENTA_GREEN(DyeColor.MAGENTA, DyeColor.GREEN),
    MAGENTA_RED(DyeColor.MAGENTA, DyeColor.RED),
    MAGENTA_BLACK(DyeColor.MAGENTA, DyeColor.BLACK),

    LIGHT_BLUE_WHITE(DyeColor.LIGHT_BLUE, DyeColor.WHITE),
    LIGHT_BLUE_ORANGE(DyeColor.LIGHT_BLUE, DyeColor.ORANGE),
    LIGHT_BLUE_MAGENTA(DyeColor.LIGHT_BLUE, DyeColor.MAGENTA),
    LIGHT_BLUE_LIGHT_BLUE(DyeColor.LIGHT_BLUE, DyeColor.LIGHT_BLUE),
    LIGHT_BLUE_YELLOW(DyeColor.LIGHT_BLUE, DyeColor.YELLOW),
    LIGHT_BLUE_LIME(DyeColor.LIGHT_BLUE, DyeColor.LIME),
    LIGHT_BLUE_PINK(DyeColor.LIGHT_BLUE, DyeColor.PINK),
    LIGHT_BLUE_GRAY(DyeColor.LIGHT_BLUE, DyeColor.GRAY),
    LIGHT_BLUE_LIGHT_GRAY(DyeColor.LIGHT_BLUE, DyeColor.LIGHT_GRAY),
    LIGHT_BLUE_CYAN(DyeColor.LIGHT_BLUE, DyeColor.CYAN),
    LIGHT_BLUE_PURPLE(DyeColor.LIGHT_BLUE, DyeColor.PURPLE),
    LIGHT_BLUE_BLUE(DyeColor.LIGHT_BLUE, DyeColor.BLUE),
    LIGHT_BLUE_BROWN(DyeColor.LIGHT_BLUE, DyeColor.BROWN),
    LIGHT_BLUE_GREEN(DyeColor.LIGHT_BLUE, DyeColor.GREEN),
    LIGHT_BLUE_RED(DyeColor.LIGHT_BLUE, DyeColor.RED),
    LIGHT_BLUE_BLACK(DyeColor.LIGHT_BLUE, DyeColor.BLACK),

    YELLOW_WHITE(DyeColor.YELLOW, DyeColor.WHITE),
    YELLOW_ORANGE(DyeColor.YELLOW, DyeColor.ORANGE),
    YELLOW_MAGENTA(DyeColor.YELLOW, DyeColor.MAGENTA),
    YELLOW_LIGHT_BLUE(DyeColor.YELLOW, DyeColor.LIGHT_BLUE),
    YELLOW_YELLOW(DyeColor.YELLOW, DyeColor.YELLOW),
    YELLOW_LIME(DyeColor.YELLOW, DyeColor.LIME),
    YELLOW_PINK(DyeColor.YELLOW, DyeColor.PINK),
    YELLOW_GRAY(DyeColor.YELLOW, DyeColor.GRAY),
    YELLOW_LIGHT_GRAY(DyeColor.YELLOW, DyeColor.LIGHT_GRAY),
    YELLOW_CYAN(DyeColor.YELLOW, DyeColor.CYAN),
    YELLOW_PURPLE(DyeColor.YELLOW, DyeColor.PURPLE),
    YELLOW_BLUE(DyeColor.YELLOW, DyeColor.BLUE),
    YELLOW_BROWN(DyeColor.YELLOW, DyeColor.BROWN),
    YELLOW_GREEN(DyeColor.YELLOW, DyeColor.GREEN),
    YELLOW_RED(DyeColor.YELLOW, DyeColor.RED),
    YELLOW_BLACK(DyeColor.YELLOW, DyeColor.BLACK),

    LIME_WHITE(DyeColor.LIME, DyeColor.WHITE),
    LIME_ORANGE(DyeColor.LIME, DyeColor.ORANGE),
    LIME_MAGENTA(DyeColor.LIME, DyeColor.MAGENTA),
    LIME_LIGHT_BLUE(DyeColor.LIME, DyeColor.LIGHT_BLUE),
    LIME_YELLOW(DyeColor.LIME, DyeColor.YELLOW),
    LIME_LIME(DyeColor.LIME, DyeColor.LIME),
    LIME_PINK(DyeColor.LIME, DyeColor.PINK),
    LIME_GRAY(DyeColor.LIME, DyeColor.GRAY),
    LIME_LIGHT_GRAY(DyeColor.LIME, DyeColor.LIGHT_GRAY),
    LIME_CYAN(DyeColor.LIME, DyeColor.CYAN),
    LIME_PURPLE(DyeColor.LIME, DyeColor.PURPLE),
    LIME_BLUE(DyeColor.LIME, DyeColor.BLUE),
    LIME_BROWN(DyeColor.LIME, DyeColor.BROWN),
    LIME_GREEN(DyeColor.LIME, DyeColor.GREEN),
    LIME_RED(DyeColor.LIME, DyeColor.RED),
    LIME_BLACK(DyeColor.LIME, DyeColor.BLACK),

    PINK_WHITE(DyeColor.PINK, DyeColor.WHITE),
    PINK_ORANGE(DyeColor.PINK, DyeColor.ORANGE),
    PINK_MAGENTA(DyeColor.PINK, DyeColor.MAGENTA),
    PINK_LIGHT_BLUE(DyeColor.PINK, DyeColor.LIGHT_BLUE),
    PINK_YELLOW(DyeColor.PINK, DyeColor.YELLOW),
    PINK_LIME(DyeColor.PINK, DyeColor.LIME),
    PINK_PINK(DyeColor.PINK, DyeColor.PINK),
    PINK_GRAY(DyeColor.PINK, DyeColor.GRAY),
    PINK_LIGHT_GRAY(DyeColor.PINK, DyeColor.LIGHT_GRAY),
    PINK_CYAN(DyeColor.PINK, DyeColor.CYAN),
    PINK_PURPLE(DyeColor.PINK, DyeColor.PURPLE),
    PINK_BLUE(DyeColor.PINK, DyeColor.BLUE),
    PINK_BROWN(DyeColor.PINK, DyeColor.BROWN),
    PINK_GREEN(DyeColor.PINK, DyeColor.GREEN),
    PINK_RED(DyeColor.PINK, DyeColor.RED),
    PINK_BLACK(DyeColor.PINK, DyeColor.BLACK),

    GRAY_WHITE(DyeColor.GRAY, DyeColor.WHITE),
    GRAY_ORANGE(DyeColor.GRAY, DyeColor.ORANGE),
    GRAY_MAGENTA(DyeColor.GRAY, DyeColor.MAGENTA),
    GRAY_LIGHT_BLUE(DyeColor.GRAY, DyeColor.LIGHT_BLUE),
    GRAY_YELLOW(DyeColor.GRAY, DyeColor.YELLOW),
    GRAY_LIME(DyeColor.GRAY, DyeColor.LIME),
    GRAY_PINK(DyeColor.GRAY, DyeColor.PINK),
    GRAY_GRAY(DyeColor.GRAY, DyeColor.GRAY),
    GRAY_LIGHT_GRAY(DyeColor.GRAY, DyeColor.LIGHT_GRAY),
    GRAY_CYAN(DyeColor.GRAY, DyeColor.CYAN),
    GRAY_PURPLE(DyeColor.GRAY, DyeColor.PURPLE),
    GRAY_BLUE(DyeColor.GRAY, DyeColor.BLUE),
    GRAY_BROWN(DyeColor.GRAY, DyeColor.BROWN),
    GRAY_GREEN(DyeColor.GRAY, DyeColor.GREEN),
    GRAY_RED(DyeColor.GRAY, DyeColor.RED),
    GRAY_BLACK(DyeColor.GRAY, DyeColor.BLACK),

    LIGHT_GRAY_WHITE(DyeColor.LIGHT_GRAY, DyeColor.WHITE),
    LIGHT_GRAY_ORANGE(DyeColor.LIGHT_GRAY, DyeColor.ORANGE),
    LIGHT_GRAY_MAGENTA(DyeColor.LIGHT_GRAY, DyeColor.MAGENTA),
    LIGHT_GRAY_LIGHT_BLUE(DyeColor.LIGHT_GRAY, DyeColor.LIGHT_BLUE),
    LIGHT_GRAY_YELLOW(DyeColor.LIGHT_GRAY, DyeColor.YELLOW),
    LIGHT_GRAY_LIME(DyeColor.LIGHT_GRAY, DyeColor.LIME),
    LIGHT_GRAY_PINK(DyeColor.LIGHT_GRAY, DyeColor.PINK),
    LIGHT_GRAY_GRAY(DyeColor.LIGHT_GRAY, DyeColor.GRAY),
    LIGHT_GRAY_LIGHT_GRAY(DyeColor.LIGHT_GRAY, DyeColor.LIGHT_GRAY),
    LIGHT_GRAY_CYAN(DyeColor.LIGHT_GRAY, DyeColor.CYAN),
    LIGHT_GRAY_PURPLE(DyeColor.LIGHT_GRAY, DyeColor.PURPLE),
    LIGHT_GRAY_BLUE(DyeColor.LIGHT_GRAY, DyeColor.BLUE),
    LIGHT_GRAY_BROWN(DyeColor.LIGHT_GRAY, DyeColor.BROWN),
    LIGHT_GRAY_GREEN(DyeColor.LIGHT_GRAY, DyeColor.GREEN),
    LIGHT_GRAY_RED(DyeColor.LIGHT_GRAY, DyeColor.RED),
    LIGHT_GRAY_BLACK(DyeColor.LIGHT_GRAY, DyeColor.BLACK),

    CYAN_WHITE(DyeColor.CYAN, DyeColor.WHITE),
    CYAN_ORANGE(DyeColor.CYAN, DyeColor.ORANGE),
    CYAN_MAGENTA(DyeColor.CYAN, DyeColor.MAGENTA),
    CYAN_LIGHT_BLUE(DyeColor.CYAN, DyeColor.LIGHT_BLUE),
    CYAN_YELLOW(DyeColor.CYAN, DyeColor.YELLOW),
    CYAN_LIME(DyeColor.CYAN, DyeColor.LIME),
    CYAN_PINK(DyeColor.CYAN, DyeColor.PINK),
    CYAN_GRAY(DyeColor.CYAN, DyeColor.GRAY),
    CYAN_LIGHT_GRAY(DyeColor.CYAN, DyeColor.LIGHT_GRAY),
    CYAN_CYAN(DyeColor.CYAN, DyeColor.CYAN),
    CYAN_PURPLE(DyeColor.CYAN, DyeColor.PURPLE),
    CYAN_BLUE(DyeColor.CYAN, DyeColor.BLUE),
    CYAN_BROWN(DyeColor.CYAN, DyeColor.BROWN),
    CYAN_GREEN(DyeColor.CYAN, DyeColor.GREEN),
    CYAN_RED(DyeColor.CYAN, DyeColor.RED),
    CYAN_BLACK(DyeColor.CYAN, DyeColor.BLACK),

    PURPLE_WHITE(DyeColor.PURPLE, DyeColor.WHITE),
    PURPLE_ORANGE(DyeColor.PURPLE, DyeColor.ORANGE),
    PURPLE_MAGENTA(DyeColor.PURPLE, DyeColor.MAGENTA),
    PURPLE_LIGHT_BLUE(DyeColor.PURPLE, DyeColor.LIGHT_BLUE),
    PURPLE_YELLOW(DyeColor.PURPLE, DyeColor.YELLOW),
    PURPLE_LIME(DyeColor.PURPLE, DyeColor.LIME),
    PURPLE_PINK(DyeColor.PURPLE, DyeColor.PINK),
    PURPLE_GRAY(DyeColor.PURPLE, DyeColor.GRAY),
    PURPLE_LIGHT_GRAY(DyeColor.PURPLE, DyeColor.LIGHT_GRAY),
    PURPLE_CYAN(DyeColor.PURPLE, DyeColor.CYAN),
    PURPLE_PURPLE(DyeColor.PURPLE, DyeColor.PURPLE),
    PURPLE_BLUE(DyeColor.PURPLE, DyeColor.BLUE),
    PURPLE_BROWN(DyeColor.PURPLE, DyeColor.BROWN),
    PURPLE_GREEN(DyeColor.PURPLE, DyeColor.GREEN),
    PURPLE_RED(DyeColor.PURPLE, DyeColor.RED),
    PURPLE_BLACK(DyeColor.PURPLE, DyeColor.BLACK),

    BLUE_WHITE(DyeColor.BLUE, DyeColor.WHITE),
    BLUE_ORANGE(DyeColor.BLUE, DyeColor.ORANGE),
    BLUE_MAGENTA(DyeColor.BLUE, DyeColor.MAGENTA),
    BLUE_LIGHT_BLUE(DyeColor.BLUE, DyeColor.LIGHT_BLUE),
    BLUE_YELLOW(DyeColor.BLUE, DyeColor.YELLOW),
    BLUE_LIME(DyeColor.BLUE, DyeColor.LIME),
    BLUE_PINK(DyeColor.BLUE, DyeColor.PINK),
    BLUE_GRAY(DyeColor.BLUE, DyeColor.GRAY),
    BLUE_LIGHT_GRAY(DyeColor.BLUE, DyeColor.LIGHT_GRAY),
    BLUE_CYAN(DyeColor.BLUE, DyeColor.CYAN),
    BLUE_PURPLE(DyeColor.BLUE, DyeColor.PURPLE),
    BLUE_BLUE(DyeColor.BLUE, DyeColor.BLUE),
    BLUE_BROWN(DyeColor.BLUE, DyeColor.BROWN),
    BLUE_GREEN(DyeColor.BLUE, DyeColor.GREEN),
    BLUE_RED(DyeColor.BLUE, DyeColor.RED),
    BLUE_BLACK(DyeColor.BLUE, DyeColor.BLACK),

    BROWN_WHITE(DyeColor.BROWN, DyeColor.WHITE),
    BROWN_ORANGE(DyeColor.BROWN, DyeColor.ORANGE),
    BROWN_MAGENTA(DyeColor.BROWN, DyeColor.MAGENTA),
    BROWN_LIGHT_BLUE(DyeColor.BROWN, DyeColor.LIGHT_BLUE),
    BROWN_YELLOW(DyeColor.BROWN, DyeColor.YELLOW),
    BROWN_LIME(DyeColor.BROWN, DyeColor.LIME),
    BROWN_PINK(DyeColor.BROWN, DyeColor.PINK),
    BROWN_GRAY(DyeColor.BROWN, DyeColor.GRAY),
    BROWN_LIGHT_GRAY(DyeColor.BROWN, DyeColor.LIGHT_GRAY),
    BROWN_CYAN(DyeColor.BROWN, DyeColor.CYAN),
    BROWN_PURPLE(DyeColor.BROWN, DyeColor.PURPLE),
    BROWN_BLUE(DyeColor.BROWN, DyeColor.BLUE),
    BROWN_BROWN(DyeColor.BROWN, DyeColor.BROWN),
    BROWN_GREEN(DyeColor.BROWN, DyeColor.GREEN),
    BROWN_RED(DyeColor.BROWN, DyeColor.RED),
    BROWN_BLACK(DyeColor.BROWN, DyeColor.BLACK),

    GREEN_WHITE(DyeColor.GREEN, DyeColor.WHITE),
    GREEN_ORANGE(DyeColor.GREEN, DyeColor.ORANGE),
    GREEN_MAGENTA(DyeColor.GREEN, DyeColor.MAGENTA),
    GREEN_LIGHT_BLUE(DyeColor.GREEN, DyeColor.LIGHT_BLUE),
    GREEN_YELLOW(DyeColor.GREEN, DyeColor.YELLOW),
    GREEN_LIME(DyeColor.GREEN, DyeColor.LIME),
    GREEN_PINK(DyeColor.GREEN, DyeColor.PINK),
    GREEN_GRAY(DyeColor.GREEN, DyeColor.GRAY),
    GREEN_LIGHT_GRAY(DyeColor.GREEN, DyeColor.LIGHT_GRAY),
    GREEN_CYAN(DyeColor.GREEN, DyeColor.CYAN),
    GREEN_PURPLE(DyeColor.GREEN, DyeColor.PURPLE),
    GREEN_BLUE(DyeColor.GREEN, DyeColor.BLUE),
    GREEN_BROWN(DyeColor.GREEN, DyeColor.BROWN),
    GREEN_GREEN(DyeColor.GREEN, DyeColor.GREEN),
    GREEN_RED(DyeColor.GREEN, DyeColor.RED),
    GREEN_BLACK(DyeColor.GREEN, DyeColor.BLACK),

    RED_WHITE(DyeColor.RED, DyeColor.WHITE),
    RED_ORANGE(DyeColor.RED, DyeColor.ORANGE),
    RED_MAGENTA(DyeColor.RED, DyeColor.MAGENTA),
    RED_LIGHT_BLUE(DyeColor.RED, DyeColor.LIGHT_BLUE),
    RED_YELLOW(DyeColor.RED, DyeColor.YELLOW),
    RED_LIME(DyeColor.RED, DyeColor.LIME),
    RED_PINK(DyeColor.RED, DyeColor.PINK),
    RED_GRAY(DyeColor.RED, DyeColor.GRAY),
    RED_LIGHT_GRAY(DyeColor.RED, DyeColor.LIGHT_GRAY),
    RED_CYAN(DyeColor.RED, DyeColor.CYAN),
    RED_PURPLE(DyeColor.RED, DyeColor.PURPLE),
    RED_BLUE(DyeColor.RED, DyeColor.BLUE),
    RED_BROWN(DyeColor.RED, DyeColor.BROWN),
    RED_GREEN(DyeColor.RED, DyeColor.GREEN),
    RED_RED(DyeColor.RED, DyeColor.RED),
    RED_BLACK(DyeColor.RED, DyeColor.BLACK),

    BLACK_WHITE(DyeColor.BLACK, DyeColor.WHITE),
    BLACK_ORANGE(DyeColor.BLACK, DyeColor.ORANGE),
    BLACK_MAGENTA(DyeColor.BLACK, DyeColor.MAGENTA),
    BLACK_LIGHT_BLUE(DyeColor.BLACK, DyeColor.LIGHT_BLUE),
    BLACK_YELLOW(DyeColor.BLACK, DyeColor.YELLOW),
    BLACK_LIME(DyeColor.BLACK, DyeColor.LIME),
    BLACK_PINK(DyeColor.BLACK, DyeColor.PINK),
    BLACK_GRAY(DyeColor.BLACK, DyeColor.GRAY),
    BLACK_LIGHT_GRAY(DyeColor.BLACK, DyeColor.LIGHT_GRAY),
    BLACK_CYAN(DyeColor.BLACK, DyeColor.CYAN),
    BLACK_PURPLE(DyeColor.BLACK, DyeColor.PURPLE),
    BLACK_BLUE(DyeColor.BLACK, DyeColor.BLUE),
    BLACK_BROWN(DyeColor.BLACK, DyeColor.BROWN),
    BLACK_GREEN(DyeColor.BLACK, DyeColor.GREEN),
    BLACK_RED(DyeColor.BLACK, DyeColor.RED),
    BLACK_BLACK(DyeColor.BLACK, DyeColor.BLACK);

    private final DyeColor brickColor;
    private final DyeColor mortarColor;

    DyedBrickType(DyeColor brickColor, DyeColor mortarColor) {
        this.brickColor = brickColor;
        this.mortarColor = mortarColor;
    }

    public DyeColor getBrickColor() {
        return brickColor;
    }

    public DyeColor getMortarColor() {
        return mortarColor;
    }

    public String getSerializedName() {
        return brickColor.getName() + "_" + mortarColor.getName();
    }

    public static DyedBrickType fromColors(DyeColor brick, DyeColor mortar) {
        for (DyedBrickType type : values()) {
            if (type.brickColor == brick && type.mortarColor == mortar) {
                return type;
            }
        }
        return WHITE_LIGHT_GRAY; // Default fallback
    }
}